name: bidrag-admin-q1
ingresses:
  - https://bidrag-admin-q1.intern.dev.nav.no
limits:
  memory: 4000Mi
requests:
  cpu: 50m
  memory: 1000Mi
replicas:
  max: 1
  min: 1
database:
  navn: bidrag-admin-q1
  tier: db-custom-1-3840
  size: 25
  auditlog: "on"
kafka:
  pool: nav-dev
env:
  BIDRAG_ORGANISASJON_SCOPE: dev-fss.bidrag.bidrag-organisasjon-feature
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon-feature.dev-fss-pub.nais.io/bidrag-organisasjon
  JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
outbound-access-apps:
  - bidrag-kodeverk
outbound-access-hosts:
  - bidrag-organisasjon-feature.dev-fss-pub.nais.io
  - bidrag-unleash-api.nav.cloud.nais.io
unleash:
  env: development
  secret_name: bidrag-admin-unleash-api-token