name: bidrag-admin
ingresses:
  - https://bidrag-admin.intern.nav.no
limits:
  memory: 1000Mi
requests:
  cpu: 50m
  memory: 200Mi
replicas:
  max: 2
  min: 2
database:
  navn: bidrag-admin-prod
  tier: db-custom-1-3840
  size: 10
  auditlog: "on"
kafka:
  pool: nav-prod
env:
  KODEVERK_URL: http://bidrag-kodeverk
  BIDRAG_SJABLON_URL: https://bidrag-sjablon.prod-fss-pub.nais.io/bidrag-sjablon
  BIDRAG_ORGANISASJON_SCOPE: prod-fss.bidrag.bidrag-organisasjon
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.prod-fss-pub.nais.io/bidrag-organisasjon
  JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
outbound-access-apps:
  - bidrag-stonad
  - bidrag-vedtak
  - bidrag-kodeverk
outbound-access-hosts:
  - bidrag-organisasjon.prod-fss-pub.nais.io
  - bidrag-unleash-api.nav.cloud.nais.io
unleash:
  env: production
  secret_name: bidrag-admin-unleash-api-token
azure_access_inbound:
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss