name: bidrag-admin-fss
ingresses:
  - https://bidrag-admin-fss.intern.dev.nav.no
limits:
  memory: 500Mi
requests:
  cpu: 50m
  memory: 100Mi
replicas:
  max: 1
  min: 1
env:
  BISYS_URL: b27wasl00799.preprod.local
azure_access_inbound:
  - application: bidrag-ui
    namespace: bidrag
    cluster: dev-fss
  - application: bidrag-ui-feature
    namespace: bidrag
    cluster: dev-fss