apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
  annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "512m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
        - id: secure_logs
  secureLogs:
      enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
      inbound:
        rules:
        {{#each azure_access_inbound}}
          - application: {{this.application}}
            namespace: {{this.namespace}}
            cluster: {{this.cluster}}
        {{/each}}
      outbound:
        external:
          - host: {{env.BISYS_URL}}
            ports:
            - port: 9445
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      memory: {{limits.memory}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
  replicas:
    disableAutoScaling: true
    max: {{replicas.max}}
    min: {{replicas.min}}
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}

