name: bidrag-admin-fss
ingresses:
  - https://bidrag-admin-fss.intern.nav.no
limits:
  memory: 500Mi
requests:
  cpu: 50m
  memory: 100Mi
replicas:
  max: 2
  min: 2
env:
  BISYS_URL: b27wasl00850.preprod.local