name: Deploy to prod gcp
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.nais/bidrag-admin/**.yaml'
      - '.github/workflows/admin_deploy_prod.yaml'
      - 'pom.xml'
      - '**/bidrag-admin-gcp/**'


jobs:
  build_and_deploy:
    name: "Build and deploy to prod"
    permissions:
      contents: "write"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy_prod.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -f bidrag-admin-gcp
      ktlint_options: -f bidrag-admin-gcp
      docker_context: ./bidrag-admin-gcp
      nais_variabler_filnavn: bidrag-admin/prod.yaml
      nais_hovedfil_navn: bidrag-admin/nais.yaml
      image_suffix: bidrag-admin
      tag: bidrag-admin

  deploy_unleash:
    runs-on: ubuntu-latest
    name: Deploy unleash
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v5
      - name: Deploy unleash to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/bidrag-admin/unleash.yaml
          VARS: .nais/bidrag-admin/prod.yaml