name: Deploy dev fss
on:
  workflow_dispatch:
  schedule:
    - cron : '0 2 * * 1'
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build_and_deploy:
    name: "Build and deploy to dev"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_cluster: fss
      maven_options: -B -q -fae -f bidrag-admin-fss
      ktlint_options: -f bidrag-admin-fss
      docker_context: ./bidrag-admin-fss
      nais_variabler_filnavn: bidrag-admin-fss/dev.yaml
      nais_hovedfil_navn: bidrag-admin-fss/nais.yaml
      image_suffix: bidrag-admin-fss
      tag: bidrag-admin-fss